### ISSUE TITLE
ml.dtw: still no success with training/classification

### ISSUE THREAD

**Issue by batchku** [cmuartfab/ml-lib#80] opened 2014-03-19 03:21 UTC
i tried what you recommended with turning "record" off and on in between different streams to classify; using the simple ramps in the help file (class 1 rising, class 2 falling), i'm still not able to "map" anything to a "2". everything returns "1".

what am i missing?

**Comment by jamiebullock** [comment] 2018-03-27 08:57
Closed as a duplicate of #145

**Closed by jamiebullock** 2018-03-27 08:57 UTC
Labels: question
