### ISSUE TITLE
MLP  invalid input length

### ISSUE THREAD

**Issue by HoArts** [cmuartfab/ml-lib#122] opened 2016-04-23 22:49 UTC
Hi there!

I have been working since final December 2014 mostly with SVM smoothly. I also "played" a lot for several months with MPL. Both in Max 6. I am returning to them now in Max 7 and for some reason I have been having trouble. I am receiving the following message:
error: invalid input length, expected 8, got 3
(this one is from the basic demo — OSC accelerators /accxyz -0.n  0.n -0.n). If I connect another device, with say 14 sensors the message is:
error: invalid input length, expected 19, got 14
That is: the input vector size does not adjust  automatically. I think that this is a very basic and obvious mistake of mine but can you help me!

Thanks in advance!
Kindest regards.

**Comment by HoArts** [comment] 2016-04-24 12:18
Please note that I am aware of the message #77. Thanks!

**Comment by HoArts** [comment] 2016-04-24 16:59
Hi there again!

I think I _discovered_ my _issue_, so I am sharing my experience: I have, firstly, to _force_ Max 7 to _trigger_ the basics such as **add**, **map**, **num_outputs**, etc,, with some clicks / enter, even if I do not change values, so that way it makes it effectively work (e.g., adjust the input vector size automatically). Although not a linear problem/solution, because sometimes it works sometimes don't, even if I proceed exactly by the same steps, it works fair enough!

Best!

**Comment by jamiebullock** [comment] 2016-04-25 11:08
Hi,

I'm reopening this, since although you have worked around the issue, it isn't clear to me what the issue is and whether it is something that needs an underlying fix. I will therefore investigate this further and try to reproduce the problem.

**Comment by HoArts** [comment] 2016-04-25 11:35
Hi again!

Dear Jamie, great, thanks. I will also keep giving feedback on my own experiences on this _issue_ to try to help as much as I can!

Best!

**Comment by jamiebullock** [comment] 2016-06-14 15:44
Hi, I'm finally getting around to looking at this.

Unfortunately, I can't reproduce the problem, in Max 7 `[ml.mlp]` adjust to the number of inputs as expected.

Would you mind attaching a minimal Max patch that reproduces your problem...? Ideally without OSC etc, just using internal Max messages.

Thanks.

**Comment by jamiebullock** [comment] 2016-07-09 11:21
Closing as can't reproduce. Will reopen if someone can provide a minimal reproducible example.

**Closed by jamiebullock** 2016-07-09 11:21 UTC
Labels: bug, can't reproduce
